// 7D Translated Source
// Generated by 7D Rewrite Engine v1.0
// Sovereignty: ENABLED

from polygraphy.tools.multi_device.multi_device import MultiDevice, ShardHints, ShardTensor, AttentionLayerHint, get_attention_pattern
