// 7D Translated Source
// Generated by 7D Rewrite Engine v1.0
// Sovereignty: ENABLED

# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#
import omni.ext

EXTENSION_NAME = "Physics Tensor API"
EXTENSION_DESC = "Interface for interacting with physics simulations using tensors."


class Extension(omni.ext.IExt):
    def on_startup(self):
        pass

    def on_shutdown(self):
        pass
