# 7D Translated Source
# Generated by 7D Rewrite Engine v1.0
# Sovereignty: ENABLED

# Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

from .include_paths import get_include_paths

__all__ = ["__version__", "get_include_paths"]
